ALTER TABLE `Plugin`
  ADD COLUMN `adminDisableReason` TEXT NULL;

ALTER TABLE `PluginVersion`
  MODIFY `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUIRED') NOT NULL DEFAULT 'PENDING',
  MODIFY `auditLog` TEXT NULL;

ALTER TABLE `PluginVersionActionLog`
  MODIFY `action` ENUM(
    'SUBMIT',
    'RESUBMIT',
    'AUDIT_APPROVED',
    'AUDIT_REJECTED',
    'AUDIT_CHANGES_REQUIRED',
    'VISIBILITY_PUBLIC',
    'VISIBILITY_PRIVATE',
    'FORCE_UNPUBLISH',
    'FORCE_REPUBLISH',
    'PLUGIN_DELETE',
    'ROLLBACK',
    'DELETE'
  ) NOT NULL;
